Bookings/urls.py
from django.urls import path

from . import views


app_name='Bookings'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('registration', views.registration, name='registration'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('bookTour', views.bookTour, name='bookTour'),
    path('bookingResult', views.bookingResult, name='bookingResult'),
    path('bookingConfirmation', views.bookingConfirmation, name='bookingConfirmation'),
    path('catalog', views.catalog, name='catalog'),
    path('myBooking', views.myBooking, name='myBooking'),
]

tour_booking/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('booking/', include('Bookings.urls')),
]

tours/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),  # Добавляем пустой путь
    path('register/', views.register_user, name='register_user'),
    path('login/', views.login_user, name='login_user'),
    path('add_tour/', views.add_tour, name='add_tour'),
]

Bookings/models.py
from django.db import models
from datetime import datetime


# Create your models here.

#Enum Class to populate the Booking Status of a tour
class Status(models.Model):
    STATUS = (
        ('МЕСТ НЕТ', "МЕСТ НЕТ"),
        ('ДОСТУПНО', "ДОСТУПНО"),
    )
    status = models.CharField(max_length=10, choices=STATUS, unique=True)

    def __str__(self):
        return self.status


class Tour(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.TextField(blank=True, null=True)
    location = models.TextField(blank=True, null=True)
    visitorCount = models.IntegerField(blank=True, null=True, default=0)
    cost = models.FloatField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Tour"
        verbose_name_plural = "Tours"


class Customer(models.Model):
    name = models.CharField(max_length=50)
    contact = models.CharField(max_length=10, unique=True)
    password = models.CharField(max_length=20)
    email = models.EmailField(blank=True,null=True)
    address = models.TextField(blank=True ,null=True)
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Customer"
        verbose_name_plural = "Customers"


class Booking(models.Model):
    h_id = models.ForeignKey("Tour", on_delete=models.CASCADE)
    c_id = models.ForeignKey("Customer", on_delete=models.CASCADE)
    time = models.DateField(auto_now_add=True)
    amount = models.FloatField(blank=True, null=True)
    status = models.ForeignKey("Status", on_delete=models.CASCADE)
    checkInDate = models.DateField(auto_now_add=True,blank=True , null=True)
    checkOutDate = models.DateField(auto_now_add=True,blank=True ,null=True)

    def __str__(self):
        return str(self.h_id)

    class Meta:
        verbose_name = "Booking"
        verbose_name_plural = "Bookings"



class Search(models.Model):
    c_id = models.ForeignKey("Customer", on_delete=models.CASCADE)
    location = models.CharField(max_length=50)
    checkInDate = models.DateField(blank=True,null=True)
    checkOutDate = models.DateField(blank=True , null=True)
    amount = models.FloatField(blank=True , null=True)

    def __str__(self):
        return str(self.c_id)

Bookings/forms.py
from django import forms
from Bookings.models import *

class LoginForm(forms.Form):
    name = forms.CharField(label='Enter Your Name' , max_length=50)
    contact = forms.CharField(label='Mobile No', max_length=10)
    password = forms.CharField(label='Password', widget=forms.PasswordInput())



class RegistrationForm(forms.Form):
    name = forms.CharField(label='Name', max_length=30)
    contact = forms.CharField(label='Contact', max_length=10)
    email = forms.EmailField(label='Email', required=False, max_length=254)
    address = forms.CharField(label='Address', required=False, max_length=200)
    password = forms.CharField(label='Password', widget=forms.PasswordInput())
    cpassword = forms.CharField(label='Confirm Password', widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        pas = cleaned_data.get('password')
        cpas = cleaned_data.get('cpassword')
        if pas != cpas:
            msg = "Пароли не совпадают блин!"
            self.add_error('cpassword', msg)


class BookTourForm(forms.Form):
    location = forms.CharField(label='Location' ,max_length=20)
    amount = forms.FloatField(label='Enter the upper limit of Your Budget')

Bookings/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect
from Bookings.models import Status,Tour,Customer,Booking
from .forms import LoginForm, RegistrationForm,BookTourForm
from django.db import transaction
# Create your views here.
def index(request):
	return render(request, 'booking/index.html')

#function to handle the login operations and load the Login form into the template
def login(request):
	return render(request, 'booking/login.html', {
		'form': LoginForm
	})

#User Registration function to handle the registration Operation by loading the Registration Form into the Registration Template
def register(request):
    return render(request, 'booking/registration.html', {
        'form': RegistrationForm
    })

#Function to handle the data received from the Registration Form
def registration(request):
    if request.method == 'POST':
        customerObj = Customer(name=request.POST['name'],contact=request.POST['contact'],
                               password=request.POST['password'],email=request.POST['email'],
                               address=request.POST['address'])
        customerObj.save()
    return render(request, 'booking/dashboard.html')

#User Dashboard helps to store and validate the data received from the Registration and Login Forms
def dashboard(request):
    if request.method == 'POST':
        name = request.POST['name']
        contact = request.POST['contact']
        password = request.POST['password']
        customerValidate = Customer.objects.filter(contact=contact).exists()
        if not customerValidate:
            return render(request, 'booking/login.html', {
                'form': LoginForm(initial={'contact': contact,'name' :name}, auto_id=False),
                'error_message': 'Вы не зарегестрированы'
            })
        if Customer.objects.get(contact=contact).password != password :
            return render(request, 'booking/login.html', {
                'form': LoginForm(initial={'contact': contact , 'name' :name}, auto_id=False),
                'error_message': 'У вас что-то не мэтчнулось, перепроверьте данные'
            })
        customerObj = Customer.objects.get(contact=contact)
        request.session['customerPk']=customerObj.pk
        print(request.session)
        return render(request , 'booking/dashboard.html',{'CustName': customerObj.name})


#Function to call and load the Tour Booking Form into the template
def bookTour(request):
    return render(request, 'booking/bookTour.html', {
        'form': BookTourForm
    })

#Function to handle the data received from the tour Booking Form
def bookingResult(request):
    if request.method == 'POST':
        tourList = list(Tour.objects.filter(location__iexact=request.POST['location']).values_list('name',flat=True))
        request.session['location'] = request.POST['location']
        if request.POST['amount']:
            request.session['amount']=request.POST['amount']

        if request.POST['checkInDate']:
            request.session['checkInDate'] = request.POST['checkInDate']

        if request.POST['checkOutDate']:
            request.session['checkOutDate'] = request.POST['checkOutDate']

        return render(request, 'booking/tourList.html', {'tourList': tourList})


#function that does the actual Booking by storing the data in the Database. The function is atomic with Rollback Functionality
#so that the booking can be reverted back in case of Connectivity Failure
@transaction.atomic
def bookingConfirmation(request):
    request.session['tourName']=request.POST['tourName']
    TourObj = Tour.objects.get(name=request.session['tourName'])
    customerObj = Customer.objects.get(pk=request.session['customerPk'])
    totalCount = TourObj.visitorCount + 1
    TourObj.visitorCount = totalCount
    TourObj.save()
    print(request.POST)
    try:
        if request.POST['Book']:
            bookingObj = Booking(h_id=TourObj,c_id=customerObj,amount=request.session['amount'],
                                 status=Status.objects.get(status="МЕСТ НЕТ"),checkInDate=request.session['checkInDate'],
                                 checkOutDate=request.session['checkOutDate'])
            bookingObj.save()
            return render(request, 'booking/booking_success.html')
    except :
        bookingObj = Booking(h_id=TourObj, c_id=customerObj, amount=request.session['amount'],
                             status=Status.objects.get(status="ДОСТУПНО"), checkInDate=request.session['checkInDate'],
                             checkOutDate=request.session['checkOutDate'])
        bookingObj.save()
        return render(request, 'booking/draft_saved.html')



#to check the number of visits to a particular tour
def catalog(request):
    tourList = Tour.objects.all()
    return render(request,'booking/catalog.html',{'tourList': tourList})

#function provides the data for displaying the draft Booking Functionality
def myBooking(request):
    print(request.session['customerPk'])
    bookingListObj = list(Booking.objects.filter(status=Status.objects.get(status="ДОСТУПНО"))
                          .filter(c_id=request.session['customerPk']))
    print(bookingListObj)
    if len(bookingListObj) == 0:
        return HttpResponse("???")
    return render(request, 'booking/my_booking.html',{'bookingListObj':bookingListObj})

Bookings/templates/booking/bookTour.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Забронировать тур</title>
    <style>
        body {
            font-family: Helvetica, sans-serif;
            background-image: url("{% static 'img/doroga_asfalt_razmetka_130996_1920x1080.jpg' %}");
            text-align: center;
        }
        .menu {
            display: flex;
            justify-content: space-between;
            background-color: rgba(0, 0, 0, 0.453);
            padding: 10px;
            color: #fff;
        }
        .menu a {
            color: #fff;
            text-decoration: none;
            margin: 0 10px;
        }
        .menu a:hover {
            text-decoration: underline;
        }
        .content {
            margin-top: 50px;
            display: inline-block;
            text-align: left;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
        }
    </style>
</head>
<body>
    <div class="menu">
        <a href="/booking/login">Войти</a>
        <a href="/booking/register">Регистрация</a>
        <a href="/booking/catalog">Каталог туров</a>
        <a href="/booking/bookTour">Забронировать тур</a>
        <a href="/booking/myBooking">Мои брони</a>
    </div>
    <div class="content">
        <h1>Забронировать тур</h1>
        <form action="{% url 'Bookings:bookingResult' %}" method="post">
            {% csrf_token %}
            <p>Город {{ form.location }}</p>
            <p>Дата начала тура <input type="date" name="checkInDate"></p>
            <p>Дата конца тура <input type="date" name="checkOutDate"></p>
            <p>Лимит бюджета {{ form.amount }}</p>
            <input type="submit" value="Отправить" />
            <p><a href="/booking">Назад</a></p>
        </form>
    </div>
</body>
</html>

Bookings/templates/booking/booking_success.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title style="color: rgb(217, 217, 233);">Успешное бронирование</title>
    <style>
        body {
            font-family: Helvetica, sans-serif;
            background-image: url("{% static 'img/doroga_asfalt_razmetka_130996_1920x1080.jpg' %}");
        }
        .menu {
            display: flex;
            justify-content: space-between;
            background-color:  rgba(0, 0, 0, 0.453);
            padding: 10px;
            color: #fff;
        }
        .menu a {
            color: #fff;
            text-decoration: none;
            margin: 0 10px;
        }
        .menu a:hover {
            text-decoration: underline;
        }
        .content {
            text-align: center;
            margin-top: 50px;
        }
        .content img {
            width: 150px;
            height: 150px;
            border-radius: 50%;
        }
        .content p {
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="menu">
        <a href="/booking/login">Войти</a>
        <a href="/booking/register">Регистрация</a>
        <a href="/booking/catalog">Каталог туров</a>
        <a href="/booking/bookTour">Забронировать тур</a>
        <a href="/booking/myBooking">Мои брони</a>
    </div>
    <div class="content">
        <h1 style="color: rgb(217, 217, 233);">Ваше бронирование прошло успешно</h1>
        <img src="{% static 'img/smoking rat.jpg' %}" alt="Изображение">
    </div>
</body>
</html>

Bookings/templates/booking/catalog.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Туры</title>
    <style>
        body {
            font-family: Helvetica, sans-serif;
            background-image: url("{% static 'img/doroga_asfalt_razmetka_130996_1920x1080.jpg' %}");
        }
        .menu {
            display: flex;
            justify-content: space-between;
            background-color:  rgba(0, 0, 0, 0.453);
            padding: 10px;
            color: #fff;
        }
        .menu a {
            color: #fff;
            text-decoration: none;
            margin: 0 10px;
        }
        .menu a:hover {
            text-decoration: underline;
        }
        .content {
            text-align: center;
            margin-top: 50px;
            padding: 0 40px;
        }
        .content ul {
            list-style-type: none;
            padding: 0;
        }
        .content li {
            color: #fff;
            margin-bottom: 10px;
            background-color:  rgba(78, 81, 88, 0.453);
            padding: 10px;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <div class="menu">
        <a href="/booking/login">Войти</a>
        <a href="/booking/register">Регистрация</a>
        <a href="/booking/catalog">Каталог</a>
        <a href="/booking/bookTour">Забронировать тур</a>
        <a href="/booking/myBooking">Мои брони</a>
    </div>
    <div class="content">
        <ul>
            {% for tour in tourList %}
                <li>
                    <h2>{{ tour.name }}</h2>
                    <p>Описание тура: {{ tour.description }}</p>
                    <p>Количество мест: {{ tour.visitorCount }}</p>
                    <p>Город: {{ tour.location }}</p>
                    <p>Стоимость: {{ tour.cost }}</p>
                </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

Bookings/templates/booking/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Добро пожаловать {{CustName}}</title>
    <style>
        body {
            font-family: Helvetica, sans-serif;
            background-image: url("{% static 'img/doroga_asfalt_razmetka_130996_1920x1080.jpg' %}");
        }
        .menu {
            display: flex;
            justify-content: space-between;
            background-color:  rgba(0, 0, 0, 0.453);
            padding: 10px;
            color: #fff;
        }
        .menu a {
            color: #fff;
            text-decoration: none;
            margin: 0 10px;
        }
        .menu a:hover {
            text-decoration: underline;
        }
        .content {
            color: #fff;
            text-align: center;
            margin-top: 50px;
        }
        .content img {
            width: 150px;
            height: 150px;
            border-radius: 50%;
        }
        .content p {
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="menu">
        <a href="/booking/login">Войти</a>
        <a href="/booking/register">Регистрация</a>
        <a href="/booking/catalog">Каталог</a>
        <a href="/booking/bookTour">Забронировать тур</a>
        <a href="/booking/myBooking">Мои брони</a>
    </div>
    <div class="content">
        <h2 style="color: rgb(217, 217, 233);">Добро пожаловать {{CustName}}</h2>
        <p style="color: rgb(217, 217, 233);">Добро пожаловать, {{CustName}}, теперь вы можете забронировать крысячий тур!</p>
        <img src="{% static 'img/cute rat.jpg' %}" alt="Изображение">
    </div>
</body>
</html>

Bookings/templates/booking/draft_saved.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title style="color: rgb(217, 217, 233);">Бронирование сохранено</title>
    <style>
        body {
            font-family: Helvetica, sans-serif;
            background-image: url("{% static 'img/doroga_asfalt_razmetka_130996_1920x1080.jpg' %}");
        }
        .menu {
            display: flex;
            justify-content: space-between;
            background-color:  rgba(0, 0, 0, 0.453);
            padding: 10px;
            color: #fff;
        }
        .menu a {
            color: #fff;
            text-decoration: none;
            margin: 0 10px;
        }
        .menu a:hover {
            text-decoration: underline;
        }
        .content {
            text-align: center;
            margin-top: 50px;
        }
        .content img {
            width: 150px;
            height: 150px;
            border-radius: 50%;
        }
        .content p {
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="menu">
        <a href="/booking/login">Войти</a>
        <a href="/booking/register">Регистрация</a>
        <a href="/booking/catalog">Каталог туров</a>
        <a href="/booking/bookTour">Забронировать тур</a>
        <a href="/booking/myBooking">Мои брони</a>
    </div>
    <div class="content">
        <h1 style="color: rgb(217, 217, 233);">Ваше бронирование успешно сохранено</h1>
        <img src="{% static 'img/happy rat.jpg' %}" alt="Изображение">
    </div>
</body>
</html>

Bookings/templates/booking/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Добро пожаловать в RatVentures DinDON</title>
    <style>
        body {
            font-family: Helvetica, sans-serif;
            background-image: url("{% static 'img/doroga_asfalt_razmetka_130996_1920x1080.jpg' %}");
        }
        .menu {
            display: flex;
            justify-content: space-between;
            background-color:  rgba(0, 0, 0, 0.453);
            padding: 10px;
            color: #fff;
        }
        .menu a {
            color: #fff;
            text-decoration: none;
            margin: 0 10px;
        }
        .menu a:hover {
            text-decoration: underline;
        }
        .content {
            text-align: center;
            margin-top: 50px;
        }
        .content img {
            width: 150px;
            height: 150px;
            border-radius: 50%;
        }
        .content p {
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="menu">
        <a href="/booking/login">Войти</a>
        <a href="/booking/register">Регистрация</a>
        <a href="/booking/catalog">Каталог</a>
        <a href="/booking/bookTour">Забронировать тур</a>
        <a href="/booking/myBooking">Мои брони</a>
    </div>
    <div class="content">
        <img src="{% static 'img/1a517cb6542629c2f6527c7b06bc1412.jpg' %}" alt="Изображение">
        <h1 style="color: rgb(217, 217, 233);"><b>Добро пожаловать на платформу по бронированию туров</b></h1>
        <p style="color: rgb(217, 217, 233);">Добро пожаловать на платформу "RatVentures DinDON"!

            <p style="color: rgb(217, 217, 233);">Эксклюзивно для ценителей путешествий с хвостиками! Мы предлагаем уникальные туры для самых изысканных крыс и их друзей. Наши маршруты спроектированы так, чтобы каждая путешествующая крыса чувствовала себя как дома.</p>
            
            <p style="color: rgb(217, 217, 233);">Почему "RatVentures DinDON"?</p>
            
            <p style="color: rgb(217, 217, 233);">🐭 Специальные маршруты для крыс. Мы заботимся о комфорте наших маленьких друзей, предоставляя удобные условия и безопасные маршруты.</p>
            
            <p style="color: rgb(217, 217, 233);">🌍 Индивидуальный подход. Каждая поездка адаптирована под потребности вашей крысы. Независимо от того, любит она приключения или предпочитает спокойные прогулки - у нас есть все!</p>
            
            <p style="color: rgb(217, 217, 233);">🏞 Увлекательные достопримечательности. Наши туры включают в себя посещение самых интересных и крысо-дружелюбных мест по всему миру.</p>
            
            <p style="color: rgb(217, 217, 233);">🏨 Гарантированные бронирования. Мы заботимся о каждой детали вашего путешествия, включая комфортное проживание в лучших гостиницах.</p>
            
            <p style="color: rgb(217, 217, 233);">💼 Профессиональные гиды. Наши сопровождающие обладают опытом и знаниями, чтобы сделать ваше путешествие незабвенным.</p>
            
            <p style="color: rgb(217, 217, 233);"> Не упустите шанс отправиться в увлекательные приключения вместе с вашей крысой! "RatVentures DinDON" - где мечты крыс сбываются!</p>
    </div>
</body>
</html>

Bookings/templates/booking/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Страница входа</title>
    <style>
        body {
            font-family: Helvetica, sans-serif;
            background-image: url("{% static 'img/doroga_asfalt_razmetka_130996_1920x1080.jpg' %}");
            text-align: center;
        }
        .menu {
            display: flex;
            justify-content: space-between;
            background-color: rgba(0, 0, 0, 0.453);
            padding: 10px;
            color: #fff;
        }
        .menu a {
            color: #fff;
            text-decoration: none;
            margin: 0 10px;
        }
        .menu a:hover {
            text-decoration: underline;
        }
        .content {
            margin-top: 50px;
            display: inline-block;
            text-align: left;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
        }
    </style>
</head>
<body>
    <div class="menu">
        <a href="/booking/login">Войти</a>
        <a href="/booking/register">Регистрация</a>
        <a href="/booking/catalog">Каталог туров</a>
        <a href="/booking/bookTour">Забронировать тур</a>
        <a href="/booking/myBooking">Мои брони</a>
    </div>
    <div class="content">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <h2>Страница входа</h2>
        <form action="{% url 'Bookings:dashboard' %}" method="post">
            {{ field.error }}
            {% csrf_token %}
            <p>Имя {{ form.name }}</p>
            <p>Номер телефона{{ form.contact }}</p>
            <p>Пароль {{ form.password }}</p>
            <input type="submit" value="Войти" /><br>
            <p><a href="/booking">На главную</a></p>
            <p><a href="/booking/register">Регистрация</a></p>
        </form>
    </div>
</body>
</html>

Bookings/templates/booking/my_booking.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Мои брони</title>
    <style>
        body {
            font-family: Helvetica, sans-serif;
            background-image: url("{% static 'img/doroga_asfalt_razmetka_130996_1920x1080.jpg' %}");
        }
        .menu {
            display: flex;
            justify-content: space-between;
            background-color:  rgba(0, 0, 0, 0.453);
            padding: 10px;
            color: #fff;
        }
        .menu a {
            color: #fff;
            text-decoration: none;
            margin: 0 10px;
        }
        .menu a:hover {
            text-decoration: underline;
        }
        .content {
            text-align: center;
            margin-top: 50px;
        }
        .content img {
            width: 150px;
            height: 150px;
            border-radius: 50%;
        }
        .content p {
            margin-bottom: 20px;
        }
        table {
            color: #fff;
            margin: 0 auto;
            border-collapse: collapse;
            width: 80%;
        }
        table, th, td {
            border: 1px solid #ccc;
        }
        th, td {
            padding: 8px;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="menu">
        <a href="/booking/login">Войти</a>
        <a href="/booking/register">Регистрация</a>
        <a href="/booking/catalog">Каталог</a>
        <a href="/booking/bookTour">Забронировать тур</a>
        <a href="/booking/myBooking">Мои брони</a>
    </div>
    <div class="content">
        <h1 style="color: rgb(217, 217, 233);">Мои брони</h1>
        <table border="1">
            <tr>
                <th>Тур</th>
                <th>Клиент</th>
                <th>Статус бронирования</th>
                <th>Стоимость</th>
                <th>Дата начала тура</th>
                <th>Дата конца тура</th>
            </tr>
            {% for booking in bookingListObj %}
                <tr>
                    <td>{{ booking.h_id.name }}</td>
                    <td>{{ booking.c_id.name }}</td>
                    <td>{{ booking.status }}</td>
                    <td>{{ booking.amount }}</td>
                    <td>{{ booking.checkInDate }}</td>
                    <td>{{ booking.checkOutDate }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
</body>
</html>

Bookings/templates/booking/registration.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
    <style>
        body {
            font-family: Helvetica, sans-serif;
            background-image: url("{% static 'img/doroga_asfalt_razmetka_130996_1920x1080.jpg' %}");
            text-align: center;
        }
        .menu {
            display: flex;
            justify-content: space-between;
            background-color: rgba(0, 0, 0, 0.453);
            padding: 10px;
            color: #fff;
        }
        .menu a {
            color: #fff;
            text-decoration: none;
            margin: 0 10px;
        }
        .menu a:hover {
            text-decoration: underline;
        }
        .content {
            margin-top: 50px;
            display: inline-block;
            text-align: left;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
        }
    </style>
</head>
<body>
    <div class="menu">
        <a href="/booking/login">Войти</a>
        <a href="/booking/register">Регистрация</a>
        <a href="/booking/catalog">Каталог туров</a>
        <a href="/booking/bookTour">Забронировать тур</a>
        <a href="/booking/myBooking">Мои брони</a>
    </div>
    <div class="content">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <h2>Регистрация</h2>
        <form action="{% url 'Bookings:registration' %}" method="post">
            {% csrf_token %}
            <p>Имя {{ form.name }} </p>
            <p>Номер телефона {{ form.contact }}</p>
            <p>Почта {{ form.email }}</p>
            <p>Город {{ form.address }}</p>
            <p>Пароль {{ form.password }}</p>
            <p>Подтвердите пароль {{ form.cpassword }} {{ form.cpassword.errors }}</p>
            <input type="submit" value="Зарегестрироваться" />
            <p><a href="/booking">Назад</a></p>
        </form>
    </div>
</body>
</html>

Bookings/templates/booking/tourList.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Туры</title>
    <style>
        body {
            font-family: Helvetica, sans-serif;
            background-image: url("{% static 'img/doroga_asfalt_razmetka_130996_1920x1080.jpg' %}");
            text-align: center;
        }
        .menu {
            display: flex;
            justify-content: space-between;
            background-color:  rgba(0, 0, 0, 0.453);
            padding: 10px;
            color: #fff;
        }
        .menu a {
            color: #fff;
            text-decoration: none;
            margin: 0 10px;
        }
        .menu a:hover {
            text-decoration: underline;
        }
        .form-container {
            margin-top: 50px;
            display: inline-block;
            text-align: left;
            background-color:  rgba(0, 0, 0, 0.453);;
            padding: 20px;
            border-radius: 5px;
        }
        .form-container p {
            font-size: 18px;
        }
        .form-container select {
            width: 100%;
            padding: 10px;
            margin-top: 10px;
            font-size: 16px;
        }
        .form-container input[type="submit"] {
            width: 150px;
            padding: 10px;
            margin-top: 20px;
            font-size: 16px;
            background-color: #333;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        .form-container input[type="submit"]:hover {
            background-color: #555;
        }
    </style>
</head>
<body>
    <div class="menu">
        <a href="/booking/login">Войти</a>
        <a href="/booking/register">Регистрация</a>
        <a href="/booking/catalog">Каталог туров</a>
        <a href="/booking/bookTour">Забронировать тур</a>
        <a href="/booking/myBooking">Мои брони</a>
    </div>
    <div class="form-container">
        <form action="{% url 'Bookings:bookingConfirmation' %}" method="post">
            {% csrf_token %}
            <p style="color: rgb(217, 217, 233);">Список доступных туров</p>
            <select name="tourName">
                {% for tour in tourList %}
                    <option value="{{ tour }}">{{tour}}</option>
                {% endfor %}
            </select>
                <!-- <input type="text" name="movieName"/> --></br></br>
                <input type="submit" value="Забронировать" name="Book" />
            <input type="submit" value="Сохранить" name="Save" />
        </form>        
    </div>
</body>
</html>